import { Hono } from "hono";
import { getCookie, setCookie, deleteCookie } from "hono/cookie";

const app = new Hono();

const ROLES = ["SUPER_ADMIN","ADMIN","FRONT_OFFICE","TERAPIS","STOCK","FINANCE","VIEWER_OWNER"];
const PERMISSIONS = {
  "dashboard.view":"Lihat dashboard",
  "patient.view":"Lihat data pasien",
  "patient.create":"Daftarkan pasien",
  "patient.edit":"Edit identitas pasien",
  "patient.photo.view":"Lihat foto perkembangan",
  "patient.photo.upload":"Unggah foto perkembangan",
  "visit.create":"Buat kunjungan",
  "visit.cancel":"Batalkan kunjungan",
  "package.view":"Lihat paket pasien",
  "package.sell":"Jual / aktifkan paket pasien",
  "package.manage":"Kelola master paket & promo",
  "payment.view":"Lihat pembayaran",
  "payment.create":"Catat pembayaran",
  "stock.view":"Lihat stok",
  "stock.manage":"Kelola produk & stok",
  "finance.view":"Lihat modul keuangan",
  "settings.view":"Lihat setting",
  "settings.manage":"Ubah setting",
  "audit.view":"Lihat audit log",
  "users.view":"Lihat user",
  "users.manage":"Kelola user & permission",
  "export.data":"Export / backup data"
};
const ROLE_DEFAULTS = {
  SUPER_ADMIN:Object.keys(PERMISSIONS),
  ADMIN:Object.keys(PERMISSIONS).filter(p=>p!=="users.manage"),
  FRONT_OFFICE:["dashboard.view","patient.view","patient.create","patient.edit","visit.create","package.view","package.sell","payment.view","payment.create"],
  TERAPIS:["dashboard.view","patient.view","patient.photo.view","patient.photo.upload","visit.create","package.view"],
  STOCK:["dashboard.view","stock.view","stock.manage"],
  FINANCE:["dashboard.view","patient.view","package.view","payment.view","payment.create","finance.view","settings.view","export.data"],
  VIEWER_OWNER:["dashboard.view","patient.view","package.view","payment.view","stock.view","finance.view","audit.view","export.data"]
};

const SCHEMA = [
`CREATE TABLE IF NOT EXISTS app_meta (key TEXT PRIMARY KEY,value TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS users (
 id TEXT PRIMARY KEY,username TEXT NOT NULL UNIQUE COLLATE NOCASE,full_name TEXT NOT NULL,password_hash TEXT NOT NULL,
 role TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS user_permissions (
 user_id TEXT NOT NULL,permission TEXT NOT NULL,allowed INTEGER NOT NULL DEFAULT 1,
 PRIMARY KEY(user_id,permission),FOREIGN KEY(user_id) REFERENCES users(id))`,
`CREATE TABLE IF NOT EXISTS sessions (
 token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL,csrf_token TEXT NOT NULL,expires_at TEXT NOT NULL,created_at TEXT NOT NULL,
 FOREIGN KEY(user_id) REFERENCES users(id))`,
`CREATE TABLE IF NOT EXISTS patients (
 id TEXT PRIMARY KEY,member_no TEXT NOT NULL UNIQUE,qr_token TEXT NOT NULL UNIQUE,name TEXT NOT NULL,address TEXT,birth_date TEXT,phone TEXT,
 default_payment_mode TEXT NOT NULL DEFAULT 'PER_VISIT',active INTEGER NOT NULL DEFAULT 1,created_by TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,
 FOREIGN KEY(created_by) REFERENCES users(id))`,
`CREATE INDEX IF NOT EXISTS idx_patients_name ON patients(name)`,
`CREATE INDEX IF NOT EXISTS idx_patients_member_no ON patients(member_no)`,
`CREATE TABLE IF NOT EXISTS packages (
 id TEXT PRIMARY KEY,code TEXT UNIQUE,name TEXT NOT NULL,sessions INTEGER,hpp REAL NOT NULL DEFAULT 0,selling_price REAL NOT NULL DEFAULT 0,
 ppn_percent REAL NOT NULL DEFAULT 0,promo_name TEXT,promo_type TEXT NOT NULL DEFAULT 'NOMINAL',promo_value REAL NOT NULL DEFAULT 0,
 active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS patient_packages (
 id TEXT PRIMARY KEY,patient_id TEXT NOT NULL,package_id TEXT NOT NULL,purchase_date TEXT NOT NULL,
 initial_sessions INTEGER NOT NULL CHECK(initial_sessions>=0),balance INTEGER NOT NULL CHECK(balance>=0),status TEXT NOT NULL DEFAULT 'AKTIF',
 purchase_price REAL NOT NULL DEFAULT 0,discount_amount REAL NOT NULL DEFAULT 0,final_amount REAL NOT NULL DEFAULT 0,
 payment_method TEXT,payment_status TEXT NOT NULL DEFAULT 'LUNAS',payment_reference TEXT,created_by TEXT,created_at TEXT NOT NULL,
 cancelled_at TEXT,cancel_reason TEXT,
 FOREIGN KEY(patient_id) REFERENCES patients(id),FOREIGN KEY(package_id) REFERENCES packages(id),FOREIGN KEY(created_by) REFERENCES users(id))`,
`CREATE INDEX IF NOT EXISTS idx_patient_packages_patient ON patient_packages(patient_id,status)`,
`CREATE TABLE IF NOT EXISTS visits (
 id TEXT PRIMARY KEY,idempotency_key TEXT NOT NULL UNIQUE,patient_id TEXT NOT NULL,visit_date TEXT NOT NULL,complaint TEXT,notes TEXT,
 patient_package_id TEXT,payment_source TEXT NOT NULL,unit_price REAL NOT NULL DEFAULT 0,discount_amount REAL NOT NULL DEFAULT 0,total_amount REAL NOT NULL DEFAULT 0,
 payment_method TEXT,payment_status TEXT NOT NULL DEFAULT 'LUNAS',status TEXT NOT NULL DEFAULT 'AKTIF',created_by TEXT NOT NULL,created_at TEXT NOT NULL,
 cancelled_by TEXT,cancelled_at TEXT,cancel_reason TEXT,
 FOREIGN KEY(patient_id) REFERENCES patients(id),FOREIGN KEY(patient_package_id) REFERENCES patient_packages(id),FOREIGN KEY(created_by) REFERENCES users(id))`,
`CREATE INDEX IF NOT EXISTS idx_visits_patient ON visits(patient_id,visit_date DESC)`,
`CREATE INDEX IF NOT EXISTS idx_visits_date ON visits(visit_date)`,
`CREATE TABLE IF NOT EXISTS package_ledger (
 id TEXT PRIMARY KEY,patient_package_id TEXT NOT NULL,patient_id TEXT NOT NULL,visit_id TEXT,entry_type TEXT NOT NULL,qty INTEGER NOT NULL,
 balance_after INTEGER NOT NULL,note TEXT,created_by TEXT NOT NULL,created_at TEXT NOT NULL,
 FOREIGN KEY(patient_package_id) REFERENCES patient_packages(id),FOREIGN KEY(patient_id) REFERENCES patients(id),FOREIGN KEY(visit_id) REFERENCES visits(id))`,
`CREATE TABLE IF NOT EXISTS payments (
 id TEXT PRIMARY KEY,patient_id TEXT NOT NULL,visit_id TEXT,patient_package_id TEXT,payment_date TEXT NOT NULL,payment_type TEXT NOT NULL,
 method TEXT,amount REAL NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'LUNAS',reference TEXT,note TEXT,created_by TEXT NOT NULL,created_at TEXT NOT NULL,
 FOREIGN KEY(patient_id) REFERENCES patients(id),FOREIGN KEY(visit_id) REFERENCES visits(id),FOREIGN KEY(patient_package_id) REFERENCES patient_packages(id))`,
`CREATE INDEX IF NOT EXISTS idx_payments_date ON payments(payment_date)`,
`CREATE TABLE IF NOT EXISTS visit_photos (
 id TEXT PRIMARY KEY,visit_id TEXT NOT NULL,patient_id TEXT NOT NULL,object_key TEXT NOT NULL UNIQUE,content_type TEXT NOT NULL,caption TEXT,
 status TEXT NOT NULL DEFAULT 'AKTIF',created_by TEXT NOT NULL,created_at TEXT NOT NULL,
 FOREIGN KEY(visit_id) REFERENCES visits(id),FOREIGN KEY(patient_id) REFERENCES patients(id))`,
`CREATE TABLE IF NOT EXISTS products (
 id TEXT PRIMARY KEY,sku TEXT UNIQUE,name TEXT NOT NULL,unit TEXT NOT NULL CHECK(unit IN ('PCS','ML')),opening_stock REAL NOT NULL DEFAULT 0,
 min_stock REAL NOT NULL DEFAULT 0,hpp REAL NOT NULL DEFAULT 0,selling_price REAL NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1,
 created_by TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS stock_movements (
 id TEXT PRIMARY KEY,product_id TEXT NOT NULL,movement_date TEXT NOT NULL,movement_type TEXT NOT NULL CHECK(movement_type IN ('IN','OUT','ADJUSTMENT')),
 qty REAL NOT NULL,note TEXT,batch_no TEXT,expiry_date TEXT,status TEXT NOT NULL DEFAULT 'AKTIF',created_by TEXT NOT NULL,created_at TEXT NOT NULL,
 cancelled_by TEXT,cancelled_at TEXT,cancel_reason TEXT,FOREIGN KEY(product_id) REFERENCES products(id))`,
`CREATE INDEX IF NOT EXISTS idx_stock_movements_product ON stock_movements(product_id,movement_date DESC)`,
`CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY,value TEXT,updated_by TEXT,updated_at TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS audit_logs (
 id TEXT PRIMARY KEY,user_id TEXT,action TEXT NOT NULL,entity_type TEXT,entity_id TEXT,description TEXT,before_json TEXT,after_json TEXT,ip TEXT,created_at TEXT NOT NULL)`,
`CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at DESC)`
];

const nowISO=()=>new Date().toISOString();
const todayID=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const id=(p="id")=>`${p}_${crypto.randomUUID().replaceAll("-","")}`;
const bytesToHex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("");
const hexToBytes=h=>{const o=new Uint8Array(h.length/2);for(let i=0;i<o.length;i++)o[i]=parseInt(h.slice(i*2,i*2+2),16);return o;};
const randomHex=(n=32)=>{const b=new Uint8Array(n);crypto.getRandomValues(b);return bytesToHex(b);};
const sha256=async t=>bytesToHex(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(t)));
async function hashPassword(password,iterations=210000){const salt=crypto.getRandomValues(new Uint8Array(16));const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations,hash:"SHA-256"},k,256);return `pbkdf2_sha256$${iterations}$${bytesToHex(salt)}$${bytesToHex(bits)}`;}
async function verifyPassword(password,encoded){try{const [alg,it,salt,expectedHex]=encoded.split("$");if(alg!=="pbkdf2_sha256")return false;const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:hexToBytes(salt),iterations:Number(it),hash:"SHA-256"},k,256);const a=new Uint8Array(bits),e=hexToBytes(expectedHex);if(a.length!==e.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a[i]^e[i];return d===0;}catch{return false;}}
const bad=(c,msg,status=400,extra={})=>c.json({ok:false,error:msg,...extra},status);
const has=(a,p)=>a?.role==="SUPER_ADMIN"||a?.permissions?.includes(p);
const ipOf=c=>c.req.header("CF-Connecting-IP")||"";

async function ensureSchema(env){
 if(!env.DB)throw new Error("D1 binding DB belum dikonfigurasi.");
 const meta=await env.DB.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='app_meta'").first();
 if(!meta){
   await env.DB.batch(SCHEMA.map(s=>env.DB.prepare(s)));
   const n=nowISO();
   await env.DB.batch([
     env.DB.prepare("INSERT OR REPLACE INTO app_meta(key,value) VALUES('schema_version','1')"),
     ...[["PKT5","Paket Infus 5x",5,5000000],["PKT10","Paket Infus 10x",10,10000000],["SOSIAL","Paket Sosial",1,0]].map(([code,name,sessions,price])=>env.DB.prepare("INSERT INTO packages(id,code,name,sessions,hpp,selling_price,ppn_percent,promo_type,promo_value,active,created_at,updated_at) VALUES(?,?,?,?,0,?,0,'NOMINAL',0,1,?,?)").bind(id("pkg"),code,name,sessions,price,n,n)),
     ...Object.entries({clinic_name:"TANGKAS",clinic_tagline:"Tata Kelola Aktivitas Kerja Selaras",default_ppn:"0",invoice_prefix:"TGS",per_visit_price:"0"}).map(([k,v])=>env.DB.prepare("INSERT INTO settings(key,value,updated_at) VALUES(?,?,?)").bind(k,v,n))
   ]);
 }
 const uc=await env.DB.prepare("SELECT COUNT(*) n FROM users").first();
 if(Number(uc?.n||0)===0&&env.ADMIN_USERNAME&&env.ADMIN_PASSWORD){const uid=id("usr"),n=nowISO(),pw=await hashPassword(env.ADMIN_PASSWORD);await env.DB.batch([env.DB.prepare("INSERT INTO users(id,username,full_name,password_hash,role,active,created_at,updated_at) VALUES(?,?,?,?,?,1,?,?)").bind(uid,env.ADMIN_USERNAME,"Super Admin",pw,"SUPER_ADMIN",n,n),...ROLE_DEFAULTS.SUPER_ADMIN.map(p=>env.DB.prepare("INSERT INTO user_permissions(user_id,permission,allowed) VALUES(?,?,1)").bind(uid,p))]);}
}
async function getAuth(c){const raw=getCookie(c,"tangkas_session");if(!raw)return null;const h=await sha256(raw);const r=await c.env.DB.prepare("SELECT s.token_hash,s.csrf_token,s.expires_at,u.id user_id,u.username,u.full_name,u.role,u.active FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=?").bind(h).first();if(!r||!r.active||r.expires_at<=nowISO()){if(r)await c.env.DB.prepare("DELETE FROM sessions WHERE token_hash=?").bind(h).run();return null;}let permissions;if(r.role==="SUPER_ADMIN")permissions=Object.keys(PERMISSIONS);else permissions=(await c.env.DB.prepare("SELECT permission FROM user_permissions WHERE user_id=? AND allowed=1").bind(r.user_id).all()).results.map(x=>x.permission);return {...r,permissions};}
async function auditStmt(env,userId,action,entityType,entityId,description,before=null,after=null,ip=""){return env.DB.prepare("INSERT INTO audit_logs(id,user_id,action,entity_type,entity_id,description,before_json,after_json,ip,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(id("aud"),userId,action,entityType,entityId,description,before?JSON.stringify(before):null,after?JSON.stringify(after):null,ip,nowISO());}

app.use("/api/*",async(c,next)=>{try{await ensureSchema(c.env);}catch(e){return bad(c,`Konfigurasi server belum lengkap: ${e.message}`,503);}if(["/api/health","/api/login","/api/setup-status"].includes(c.req.path))return next();const a=await getAuth(c);if(!a)return bad(c,"Sesi berakhir. Silakan login kembali.",401);c.set("auth",a);if(!["GET","HEAD","OPTIONS"].includes(c.req.method)){const csrf=c.req.header("X-CSRF-Token");if(!csrf||csrf!==a.csrf_token)return bad(c,"Token keamanan tidak valid.",403);}return next();});
app.get("/api/health",async c=>{try{await ensureSchema(c.env);return c.json({ok:true,status:"healthy"});}catch(e){return bad(c,e.message,503);}});
app.get("/api/setup-status",async c=>{try{await ensureSchema(c.env);const r=await c.env.DB.prepare("SELECT COUNT(*) n FROM users").first();return c.json({ok:true,ready:Number(r.n)>0,needsAdminEnv:Number(r.n)===0});}catch(e){return bad(c,e.message,503);}});
app.post("/api/login",async c=>{const b=await c.req.json().catch(()=>({}));const u=await c.env.DB.prepare("SELECT * FROM users WHERE username=? COLLATE NOCASE AND active=1").bind(String(b.username||"").trim()).first();if(!u||!(await verifyPassword(String(b.password||""),u.password_hash)))return bad(c,"Username atau password salah.",401);const raw=randomHex(),h=await sha256(raw),csrf=randomHex(24),hours=Math.min(Math.max(Number(c.env.SESSION_HOURS||12),1),72),exp=new Date(Date.now()+hours*3600000).toISOString();await c.env.DB.batch([c.env.DB.prepare("DELETE FROM sessions WHERE expires_at<=?").bind(nowISO()),c.env.DB.prepare("INSERT INTO sessions(token_hash,user_id,csrf_token,expires_at,created_at) VALUES(?,?,?,?,?)").bind(h,u.id,csrf,exp,nowISO()),await auditStmt(c.env,u.id,"LOGIN","user",u.id,`Login ${u.username}`,null,null,ipOf(c))]);setCookie(c,"tangkas_session",raw,{httpOnly:true,secure:true,sameSite:"Lax",path:"/",maxAge:hours*3600});return c.json({ok:true,csrf});});
app.post("/api/logout",async c=>{const a=c.get("auth"),raw=getCookie(c,"tangkas_session");if(raw){const h=await sha256(raw);await c.env.DB.batch([c.env.DB.prepare("DELETE FROM sessions WHERE token_hash=?").bind(h),await auditStmt(c.env,a.user_id,"LOGOUT","user",a.user_id,"Logout",null,null,ipOf(c))]);}deleteCookie(c,"tangkas_session",{path:"/"});return c.json({ok:true});});
app.get("/api/me",c=>{const a=c.get("auth");return c.json({ok:true,user:{id:a.user_id,username:a.username,full_name:a.full_name,role:a.role,permissions:a.permissions},csrf:a.csrf_token,permissionCatalog:PERMISSIONS,roles:ROLES});});

app.get("/api/dashboard",async c=>{const a=c.get("auth");if(!has(a,"dashboard.view"))return bad(c,"Tidak punya akses dashboard.",403);const t=todayID();const [p,v,pk,pay,prod,recent]=await Promise.all([c.env.DB.prepare("SELECT COUNT(*) n FROM patients WHERE active=1").first(),c.env.DB.prepare("SELECT COUNT(*) n FROM visits WHERE visit_date=? AND status='AKTIF'").bind(t).first(),c.env.DB.prepare("SELECT COUNT(*) n FROM patient_packages WHERE status='AKTIF' AND balance>0").first(),c.env.DB.prepare("SELECT COALESCE(SUM(amount),0) total FROM payments WHERE payment_date=? AND status='LUNAS'").bind(t).first(),c.env.DB.prepare("SELECT p.id,p.min_stock,p.opening_stock+COALESCE(SUM(CASE WHEN sm.status='AKTIF' AND sm.movement_type='IN' THEN sm.qty WHEN sm.status='AKTIF' AND sm.movement_type='OUT' THEN -sm.qty WHEN sm.status='AKTIF' AND sm.movement_type='ADJUSTMENT' THEN sm.qty ELSE 0 END),0) balance FROM products p LEFT JOIN stock_movements sm ON sm.product_id=p.id WHERE p.active=1 GROUP BY p.id").all(),c.env.DB.prepare("SELECT v.id,v.visit_date,v.status,p.member_no,p.name,pk.name package_name FROM visits v JOIN patients p ON p.id=v.patient_id LEFT JOIN patient_packages pp ON pp.id=v.patient_package_id LEFT JOIN packages pk ON pk.id=pp.package_id ORDER BY v.created_at DESC LIMIT 8").all()]);return c.json({ok:true,kpi:{patients:Number(p.n),visitsToday:Number(v.n),activePackages:Number(pk.n),revenueToday:Number(pay.total||0),lowStock:prod.results.filter(x=>Number(x.balance)<=Number(x.min_stock)).length},recent:recent.results});});

async function nextMemberNo(env){const ym=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit"}).format(new Date()).replace("-","");const prefix=`TGS-${ym}-`;const r=await env.DB.prepare("SELECT member_no FROM patients WHERE member_no LIKE ? ORDER BY member_no DESC LIMIT 1").bind(`${prefix}%`).first();let n=1;if(r){const x=Number(r.member_no.split("-").pop());if(Number.isFinite(x))n=x+1;}return `${prefix}${String(n).padStart(5,"0")}`;}
app.get("/api/patients",async c=>{const a=c.get("auth");if(!has(a,"patient.view"))return bad(c,"Tidak punya akses pasien.",403);const q=String(c.req.query("q")||"").trim(),limit=Math.min(Number(c.req.query("limit")||50),100);let r;if(q){const like=`%${q}%`;r=await c.env.DB.prepare("SELECT id,member_no,qr_token,name,address,birth_date,phone,default_payment_mode,active,created_at FROM patients WHERE active=1 AND (member_no LIKE ? OR name LIKE ? OR qr_token=?) ORDER BY name LIMIT ?").bind(like,like,q,limit).all();}else r=await c.env.DB.prepare("SELECT id,member_no,qr_token,name,address,birth_date,phone,default_payment_mode,active,created_at FROM patients WHERE active=1 ORDER BY created_at DESC LIMIT ?").bind(limit).all();return c.json({ok:true,patients:r.results});});
app.post("/api/patients",async c=>{const a=c.get("auth");if(!has(a,"patient.create"))return bad(c,"Tidak punya akses membuat pasien.",403);const b=await c.req.json().catch(()=>({})),name=String(b.name||"").trim();if(!name)return bad(c,"Nama wajib diisi.");const member=await nextMemberNo(c.env),pid=id("pat"),qr=`TQ-${randomHex(8).toUpperCase()}`,n=nowISO();await c.env.DB.batch([c.env.DB.prepare("INSERT INTO patients(id,member_no,qr_token,name,address,birth_date,phone,default_payment_mode,active,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,1,?,?,?)").bind(pid,member,qr,name,String(b.address||"").trim(),b.birth_date||null,String(b.phone||"").trim(),b.default_payment_mode==="PACKAGE"?"PACKAGE":"PER_VISIT",a.user_id,n,n),await auditStmt(c.env,a.user_id,"CREATE_PATIENT","patient",pid,`Member ${member} - ${name}`,null,{member,name},ipOf(c))]);return c.json({ok:true,id:pid,member_no:member,qr_token:qr},201);});
app.get("/api/patients/:id",async c=>{const a=c.get("auth");if(!has(a,"patient.view"))return bad(c,"Tidak punya akses pasien.",403);const pid=c.req.param("id"),patient=await c.env.DB.prepare("SELECT * FROM patients WHERE id=?").bind(pid).first();if(!patient)return bad(c,"Pasien tidak ditemukan.",404);const [packages,visits,payments,photos]=await Promise.all([c.env.DB.prepare("SELECT pp.*,pk.name package_name,pk.code package_code FROM patient_packages pp JOIN packages pk ON pk.id=pp.package_id WHERE pp.patient_id=? ORDER BY pp.created_at DESC").bind(pid).all(),c.env.DB.prepare("SELECT v.*,u.full_name created_by_name,pk.name package_name,pp.balance current_package_balance FROM visits v LEFT JOIN users u ON u.id=v.created_by LEFT JOIN patient_packages pp ON pp.id=v.patient_package_id LEFT JOIN packages pk ON pk.id=pp.package_id WHERE v.patient_id=? ORDER BY v.visit_date DESC,v.created_at DESC LIMIT 100").bind(pid).all(),has(a,"payment.view")?c.env.DB.prepare("SELECT * FROM payments WHERE patient_id=? ORDER BY payment_date DESC,created_at DESC LIMIT 100").bind(pid).all():Promise.resolve({results:[]}),has(a,"patient.photo.view")?c.env.DB.prepare("SELECT vp.id,vp.visit_id,vp.caption,vp.content_type,vp.created_at,v.visit_date FROM visit_photos vp JOIN visits v ON v.id=vp.visit_id WHERE vp.patient_id=? AND vp.status='AKTIF' ORDER BY vp.created_at DESC").bind(pid).all():Promise.resolve({results:[]})]);return c.json({ok:true,patient,packages:packages.results,visits:visits.results,payments:payments.results,photos:photos.results});});
app.put("/api/patients/:id",async c=>{const a=c.get("auth");if(!has(a,"patient.edit"))return bad(c,"Tidak punya akses edit pasien.",403);const pid=c.req.param("id"),before=await c.env.DB.prepare("SELECT * FROM patients WHERE id=?").bind(pid).first();if(!before)return bad(c,"Pasien tidak ditemukan.",404);const b=await c.req.json().catch(()=>({})),name=String(b.name||"").trim();if(!name)return bad(c,"Nama wajib diisi.");const after={name,address:String(b.address||"").trim(),birth_date:b.birth_date||null,phone:String(b.phone||"").trim(),default_payment_mode:b.default_payment_mode==="PACKAGE"?"PACKAGE":"PER_VISIT"};await c.env.DB.batch([c.env.DB.prepare("UPDATE patients SET name=?,address=?,birth_date=?,phone=?,default_payment_mode=?,updated_at=? WHERE id=?").bind(after.name,after.address,after.birth_date,after.phone,after.default_payment_mode,nowISO(),pid),await auditStmt(c.env,a.user_id,"UPDATE_PATIENT","patient",pid,`Edit ${before.member_no}`,before,after,ipOf(c))]);return c.json({ok:true});});

app.get("/api/packages",async c=>{const a=c.get("auth");if(!has(a,"package.view")&&!has(a,"package.manage"))return bad(c,"Tidak punya akses paket.",403);const all=c.req.query("all")==="1";const r=await c.env.DB.prepare(`SELECT * FROM packages ${all?"":"WHERE active=1"} ORDER BY name`).all();return c.json({ok:true,packages:r.results});});
app.post("/api/packages",async c=>{const a=c.get("auth");if(!has(a,"package.manage"))return bad(c,"Tidak punya akses kelola paket.",403);const b=await c.req.json().catch(()=>({})),name=String(b.name||"").trim();if(!name)return bad(c,"Nama paket wajib.");const pid=id("pkg"),n=nowISO();await c.env.DB.batch([c.env.DB.prepare("INSERT INTO packages(id,code,name,sessions,hpp,selling_price,ppn_percent,promo_name,promo_type,promo_value,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,1,?,?)").bind(pid,String(b.code||"").trim()||null,name,b.sessions?Number(b.sessions):null,Number(b.hpp||0),Number(b.selling_price||0),Number(b.ppn_percent||0),String(b.promo_name||"").trim()||null,b.promo_type==="PERCENT"?"PERCENT":"NOMINAL",Number(b.promo_value||0),n,n),await auditStmt(c.env,a.user_id,"CREATE_PACKAGE_MASTER","package",pid,`Paket ${name}`,null,b,ipOf(c))]);return c.json({ok:true,id:pid},201);});
app.put("/api/packages/:id",async c=>{const a=c.get("auth");if(!has(a,"package.manage"))return bad(c,"Tidak punya akses kelola paket.",403);const pid=c.req.param("id"),before=await c.env.DB.prepare("SELECT * FROM packages WHERE id=?").bind(pid).first();if(!before)return bad(c,"Paket tidak ditemukan.",404);const b=await c.req.json().catch(()=>({}));await c.env.DB.batch([c.env.DB.prepare("UPDATE packages SET code=?,name=?,sessions=?,hpp=?,selling_price=?,ppn_percent=?,promo_name=?,promo_type=?,promo_value=?,active=?,updated_at=? WHERE id=?").bind(String(b.code||"").trim()||null,String(b.name||before.name).trim(),b.sessions?Number(b.sessions):null,Number(b.hpp||0),Number(b.selling_price||0),Number(b.ppn_percent||0),String(b.promo_name||"").trim()||null,b.promo_type==="PERCENT"?"PERCENT":"NOMINAL",Number(b.promo_value||0),b.active?1:0,nowISO(),pid),await auditStmt(c.env,a.user_id,"UPDATE_PACKAGE_MASTER","package",pid,`Update paket ${before.name}`,before,b,ipOf(c))]);return c.json({ok:true});});
app.post("/api/patients/:id/packages",async c=>{const a=c.get("auth");if(!has(a,"package.sell")||!has(a,"payment.create"))return bad(c,"Tidak punya akses penjualan paket.",403);const patientId=c.req.param("id"),patient=await c.env.DB.prepare("SELECT * FROM patients WHERE id=?").bind(patientId).first();if(!patient)return bad(c,"Pasien tidak ditemukan.",404);const b=await c.req.json().catch(()=>({})),pkg=await c.env.DB.prepare("SELECT * FROM packages WHERE id=? AND active=1").bind(b.package_id).first();if(!pkg)return bad(c,"Paket tidak ditemukan / nonaktif.");const sessions=Number(pkg.sessions||0);if(sessions<=0)return bad(c,"Jumlah sesi paket harus lebih dari 0.");const pp=id("pp"),pay=id("pay"),n=nowISO(),date=b.purchase_date||todayID(),price=Number(pkg.selling_price||0);let disc=pkg.promo_type==="PERCENT"?Math.min(price,price*Number(pkg.promo_value||0)/100):Math.min(price,Number(pkg.promo_value||0));if(b.discount_amount!==undefined&&b.discount_amount!=="")disc=Math.max(0,Math.min(price,Number(b.discount_amount)));const final=Math.max(0,price-disc),method=String(b.payment_method||"TUNAI"),status=String(b.payment_status||"LUNAS");await c.env.DB.batch([c.env.DB.prepare("INSERT INTO patient_packages(id,patient_id,package_id,purchase_date,initial_sessions,balance,status,purchase_price,discount_amount,final_amount,payment_method,payment_status,payment_reference,created_by,created_at) VALUES(?,?,?,?,?,?,'AKTIF',?,?,?,?,?,?,?,?)").bind(pp,patientId,pkg.id,date,sessions,sessions,price,disc,final,method,status,String(b.payment_reference||"").trim()||null,a.user_id,n),c.env.DB.prepare("INSERT INTO package_ledger(id,patient_package_id,patient_id,entry_type,qty,balance_after,note,created_by,created_at) VALUES(?,?,?,'PURCHASE',?,?,?,?,?)").bind(id("led"),pp,patientId,sessions,sessions,`Pembelian ${pkg.name}`,a.user_id,n),c.env.DB.prepare("INSERT INTO payments(id,patient_id,patient_package_id,payment_date,payment_type,method,amount,status,reference,note,created_by,created_at) VALUES(?,?,?,?,'PACKAGE_PURCHASE',?,?,?,?,?,?,?)").bind(pay,patientId,pp,date,method,final,status,String(b.payment_reference||"").trim()||null,`Pembelian ${pkg.name}`,a.user_id,n),c.env.DB.prepare("UPDATE patients SET default_payment_mode='PACKAGE',updated_at=? WHERE id=?").bind(n,patientId),await auditStmt(c.env,a.user_id,"SELL_PACKAGE","patient_package",pp,`${patient.member_no} membeli ${pkg.name}; saldo ${sessions}`,null,{price,disc,final,method,status},ipOf(c))]);return c.json({ok:true,patient_package_id:pp,balance:sessions},201);});

app.get("/api/patients/:id/visit-context",async c=>{const a=c.get("auth");if(!has(a,"visit.create"))return bad(c,"Tidak punya akses membuat kunjungan.",403);const pid=c.req.param("id"),patient=await c.env.DB.prepare("SELECT id,member_no,name,default_payment_mode FROM patients WHERE id=? AND active=1").bind(pid).first();if(!patient)return bad(c,"Pasien tidak ditemukan.",404);const active=await c.env.DB.prepare("SELECT pp.id,pp.balance,pp.purchase_date,pk.name package_name,pk.code FROM patient_packages pp JOIN packages pk ON pk.id=pp.package_id WHERE pp.patient_id=? AND pp.status='AKTIF' AND pp.balance>0 ORDER BY pp.purchase_date ASC,pp.created_at ASC").bind(pid).all(),price=await c.env.DB.prepare("SELECT value FROM settings WHERE key='per_visit_price'").first();return c.json({ok:true,patient,activePackages:active.results,perVisitPrice:Number(price?.value||0),today:todayID()});});
app.post("/api/patients/:id/visits",async c=>{const a=c.get("auth");if(!has(a,"visit.create"))return bad(c,"Tidak punya akses membuat kunjungan.",403);const patientId=c.req.param("id"),patient=await c.env.DB.prepare("SELECT * FROM patients WHERE id=? AND active=1").bind(patientId).first();if(!patient)return bad(c,"Pasien tidak ditemukan.",404);const b=await c.req.json().catch(()=>({})),idem=String(b.idempotency_key||"").trim();if(!idem)return bad(c,"Idempotency key tidak ada.");const old=await c.env.DB.prepare("SELECT id FROM visits WHERE idempotency_key=?").bind(idem).first();if(old)return c.json({ok:true,id:old.id,duplicate:true});const vid=id("vis"),n=nowISO(),date=b.visit_date||todayID(),complaint=String(b.complaint||"").trim(),notes=String(b.notes||"").trim(),active=(await c.env.DB.prepare("SELECT pp.id,pp.balance,pp.status,pk.name package_name FROM patient_packages pp JOIN packages pk ON pk.id=pp.package_id WHERE pp.patient_id=? AND pp.status='AKTIF' AND pp.balance>0 ORDER BY pp.purchase_date ASC,pp.created_at ASC").bind(patientId).all()).results;let chosen=null;if(active.length===1)chosen=active[0];if(active.length>1){chosen=active.find(x=>x.id===b.patient_package_id);if(!chosen)return bad(c,"Pasien mempunyai lebih dari satu paket aktif. Pilih paket yang digunakan.");}
 if(chosen){try{await c.env.DB.batch([c.env.DB.prepare("INSERT INTO visits(id,idempotency_key,patient_id,visit_date,complaint,notes,patient_package_id,payment_source,unit_price,discount_amount,total_amount,payment_status,status,created_by,created_at) VALUES(?,?,?,?,?,?,?,'PACKAGE',0,0,0,'PAID_PREPAID','AKTIF',?,?)").bind(vid,idem,patientId,date,complaint,notes,chosen.id,a.user_id,n),c.env.DB.prepare("UPDATE patient_packages SET balance=CASE WHEN status='AKTIF' AND balance>0 THEN balance-1 ELSE -1 END,status=CASE WHEN balance=1 THEN 'HABIS' ELSE status END WHERE id=?").bind(chosen.id),c.env.DB.prepare("INSERT INTO package_ledger(id,patient_package_id,patient_id,visit_id,entry_type,qty,balance_after,note,created_by,created_at) VALUES(?,?,?,?,'USE',-1,(SELECT balance FROM patient_packages WHERE id=?),?,?,?)").bind(id("led"),chosen.id,patientId,vid,chosen.id,`Kunjungan ${date}`,a.user_id,n),await auditStmt(c.env,a.user_id,"CREATE_VISIT","visit",vid,`${patient.member_no} kunjungan; ${chosen.package_name} -1`,null,{date,package:chosen.id},ipOf(c))]);}catch(e){const dup=await c.env.DB.prepare("SELECT id FROM visits WHERE idempotency_key=?").bind(idem).first().catch(()=>null);if(dup)return c.json({ok:true,id:dup.id,duplicate:true});return bad(c,"Kunjungan gagal disimpan. Saldo paket tidak berubah.",409,{detail:e.message});}const bal=await c.env.DB.prepare("SELECT balance,status FROM patient_packages WHERE id=?").bind(chosen.id).first();return c.json({ok:true,id:vid,payment_source:"PACKAGE",package_balance:bal.balance,package_status:bal.status},201);}
 if(!has(a,"payment.create"))return bad(c,"Pasien tidak mempunyai paket aktif dan user ini tidak boleh mencatat pembayaran.",403);const unit=Math.max(0,Number(b.unit_price||0)),disc=Math.max(0,Math.min(unit,Number(b.discount_amount||0))),total=Math.max(0,unit-disc),method=String(b.payment_method||"TUNAI"),status=String(b.payment_status||"LUNAS");try{await c.env.DB.batch([c.env.DB.prepare("INSERT INTO visits(id,idempotency_key,patient_id,visit_date,complaint,notes,payment_source,unit_price,discount_amount,total_amount,payment_method,payment_status,status,created_by,created_at) VALUES(?,?,?,?,?,?,'PER_VISIT',?,?,?,?,?,'AKTIF',?,?)").bind(vid,idem,patientId,date,complaint,notes,unit,disc,total,method,status,a.user_id,n),c.env.DB.prepare("INSERT INTO payments(id,patient_id,visit_id,payment_date,payment_type,method,amount,status,reference,note,created_by,created_at) VALUES(?,?,?,?,'VISIT',?,?,?,?,?,?,?)").bind(id("pay"),patientId,vid,date,method,total,status,String(b.payment_reference||"").trim()||null,"Pembayaran per kedatangan",a.user_id,n),c.env.DB.prepare("UPDATE patients SET default_payment_mode='PER_VISIT',updated_at=? WHERE id=?").bind(n,patientId),await auditStmt(c.env,a.user_id,"CREATE_VISIT","visit",vid,`${patient.member_no} kunjungan bayar per kedatangan`,null,{date,total,method,status},ipOf(c))]);}catch(e){const dup=await c.env.DB.prepare("SELECT id FROM visits WHERE idempotency_key=?").bind(idem).first().catch(()=>null);if(dup)return c.json({ok:true,id:dup.id,duplicate:true});return bad(c,"Kunjungan/pembayaran gagal disimpan. Tidak ada transaksi parsial.",409,{detail:e.message});}return c.json({ok:true,id:vid,payment_source:"PER_VISIT",total},201);});
app.post("/api/visits/:id/cancel",async c=>{const a=c.get("auth");if(!has(a,"visit.cancel"))return bad(c,"Tidak punya akses membatalkan kunjungan.",403);const vid=c.req.param("id"),v=await c.env.DB.prepare("SELECT * FROM visits WHERE id=?").bind(vid).first();if(!v)return bad(c,"Kunjungan tidak ditemukan.",404);if(v.status!=="AKTIF")return bad(c,"Kunjungan sudah tidak aktif.");const b=await c.req.json().catch(()=>({})),reason=String(b.reason||"").trim();if(reason.length<3)return bad(c,"Alasan pembatalan wajib diisi.");const n=nowISO();if(v.patient_package_id){await c.env.DB.batch([c.env.DB.prepare("UPDATE visits SET status='DIBATALKAN',cancel_reason=?,cancelled_by=?,cancelled_at=? WHERE id=? AND status='AKTIF'").bind(reason,a.user_id,n,vid),c.env.DB.prepare("UPDATE patient_packages SET balance=balance+1,status='AKTIF' WHERE id=?").bind(v.patient_package_id),c.env.DB.prepare("INSERT INTO package_ledger(id,patient_package_id,patient_id,visit_id,entry_type,qty,balance_after,note,created_by,created_at) VALUES(?,?,?,?,'REVERSAL',1,(SELECT balance FROM patient_packages WHERE id=?),?,?,?)").bind(id("led"),v.patient_package_id,v.patient_id,vid,v.patient_package_id,`Pembatalan kunjungan: ${reason}`,a.user_id,n),await auditStmt(c.env,a.user_id,"CANCEL_VISIT","visit",vid,reason,v,{status:"DIBATALKAN",balanceReversed:true},ipOf(c))]);}else{const p=await c.env.DB.prepare("SELECT * FROM payments WHERE visit_id=? ORDER BY created_at DESC LIMIT 1").bind(vid).first(),next=p?.status==="LUNAS"?"PERLU_REFUND":"VOID";await c.env.DB.batch([c.env.DB.prepare("UPDATE visits SET status='DIBATALKAN',cancel_reason=?,cancelled_by=?,cancelled_at=?,payment_status=? WHERE id=? AND status='AKTIF'").bind(reason,a.user_id,n,next,vid),c.env.DB.prepare("UPDATE payments SET status=? WHERE visit_id=?").bind(next,vid),await auditStmt(c.env,a.user_id,"CANCEL_VISIT","visit",vid,`${reason}; pembayaran ${next}`,v,{status:"DIBATALKAN",payment_status:next},ipOf(c))]);}return c.json({ok:true});});

app.post("/api/visits/:id/photos",async c=>{const a=c.get("auth");if(!has(a,"patient.photo.upload"))return bad(c,"Tidak punya akses unggah foto.",403);if(!c.env.PHOTOS)return bad(c,"R2 binding PHOTOS belum dikonfigurasi.",503);const vid=c.req.param("id"),v=await c.env.DB.prepare("SELECT id,patient_id,status FROM visits WHERE id=?").bind(vid).first();if(!v)return bad(c,"Kunjungan tidak ditemukan.",404);const f=await c.req.formData(),file=f.get("photo"),caption=String(f.get("caption")||"").trim();if(!(file instanceof File))return bad(c,"File foto tidak ditemukan.");if(!["image/jpeg","image/png","image/webp"].includes(file.type))return bad(c,"Format foto harus JPG, PNG, atau WEBP.");if(file.size>5*1024*1024)return bad(c,"Ukuran foto maksimal 5 MB.");const pid=id("pho"),ext=file.type==="image/png"?"png":file.type==="image/webp"?"webp":"jpg",key=`patients/${v.patient_id}/visits/${vid}/${pid}.${ext}`;await c.env.PHOTOS.put(key,file.stream(),{httpMetadata:{contentType:file.type}});try{await c.env.DB.batch([c.env.DB.prepare("INSERT INTO visit_photos(id,visit_id,patient_id,object_key,content_type,caption,status,created_by,created_at) VALUES(?,?,?,?,?,?,'AKTIF',?,?)").bind(pid,vid,v.patient_id,key,file.type,caption||null,a.user_id,nowISO()),await auditStmt(c.env,a.user_id,"UPLOAD_PATIENT_PHOTO","visit_photo",pid,`Foto kunjungan ${vid}`,null,{visit_id:vid},ipOf(c))]);}catch(e){await c.env.PHOTOS.delete(key);return bad(c,"Metadata foto gagal disimpan.",500);}return c.json({ok:true,id:pid},201);});
app.get("/media/photos/:id",async c=>{try{await ensureSchema(c.env);}catch(e){return new Response(e.message,{status:503});}const a=await getAuth(c);if(!a)return new Response("Unauthorized",{status:401});if(!has(a,"patient.photo.view"))return new Response("Forbidden",{status:403});if(!c.env.PHOTOS)return new Response("R2 belum dikonfigurasi",{status:503});const r=await c.env.DB.prepare("SELECT * FROM visit_photos WHERE id=? AND status='AKTIF'").bind(c.req.param("id")).first();if(!r)return new Response("Not found",{status:404});const o=await c.env.PHOTOS.get(r.object_key);if(!o)return new Response("Not found",{status:404});const h=new Headers();o.writeHttpMetadata(h);h.set("Cache-Control","private, max-age=300");h.set("X-Content-Type-Options","nosniff");return new Response(o.body,{headers:h});});

app.get("/api/stock",async c=>{const a=c.get("auth");if(!has(a,"stock.view"))return bad(c,"Tidak punya akses stok.",403);const products=await c.env.DB.prepare("SELECT p.*,p.opening_stock+COALESCE(SUM(CASE WHEN sm.status='AKTIF' AND sm.movement_type='IN' THEN sm.qty WHEN sm.status='AKTIF' AND sm.movement_type='OUT' THEN -sm.qty WHEN sm.status='AKTIF' AND sm.movement_type='ADJUSTMENT' THEN sm.qty ELSE 0 END),0) balance FROM products p LEFT JOIN stock_movements sm ON sm.product_id=p.id WHERE p.active=1 GROUP BY p.id ORDER BY p.name").all(),recent=await c.env.DB.prepare("SELECT sm.*,p.name product_name,p.unit,u.full_name created_by_name FROM stock_movements sm JOIN products p ON p.id=sm.product_id LEFT JOIN users u ON u.id=sm.created_by ORDER BY sm.created_at DESC LIMIT 50").all();return c.json({ok:true,products:products.results,recent:recent.results});});
app.post("/api/products",async c=>{const a=c.get("auth");if(!has(a,"stock.manage"))return bad(c,"Tidak punya akses kelola stok.",403);const b=await c.req.json().catch(()=>({})),name=String(b.name||"").trim(),unit=String(b.unit||"PCS").toUpperCase();if(!name||!["PCS","ML"].includes(unit))return bad(c,"Nama dan satuan produk wajib valid.");const pid=id("prd"),n=nowISO();await c.env.DB.batch([c.env.DB.prepare("INSERT INTO products(id,sku,name,unit,opening_stock,min_stock,hpp,selling_price,active,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,1,?,?,?)").bind(pid,String(b.sku||"").trim()||null,name,unit,Number(b.opening_stock||0),Number(b.min_stock||0),Number(b.hpp||0),Number(b.selling_price||0),a.user_id,n,n),await auditStmt(c.env,a.user_id,"CREATE_PRODUCT","product",pid,`${name} (${unit})`,null,b,ipOf(c))]);return c.json({ok:true,id:pid},201);});
app.post("/api/stock/movements",async c=>{const a=c.get("auth");if(!has(a,"stock.manage"))return bad(c,"Tidak punya akses kelola stok.",403);const b=await c.req.json().catch(()=>({})),p=await c.env.DB.prepare("SELECT * FROM products WHERE id=? AND active=1").bind(b.product_id).first();if(!p)return bad(c,"Produk tidak ditemukan.");const type=String(b.movement_type||"").toUpperCase();if(!["IN","OUT","ADJUSTMENT"].includes(type))return bad(c,"Jenis movement tidak valid.");let qty=Number(b.qty);if(!Number.isFinite(qty)||qty===0)return bad(c,"Qty tidak valid.");if(["IN","OUT"].includes(type))qty=Math.abs(qty);const mid=id("sm"),n=nowISO();await c.env.DB.batch([c.env.DB.prepare("INSERT INTO stock_movements(id,product_id,movement_date,movement_type,qty,note,batch_no,expiry_date,status,created_by,created_at) VALUES(?,?,?,?,?,?,NULL,NULL,'AKTIF',?,?)").bind(mid,p.id,b.movement_date||todayID(),type,qty,String(b.note||"").trim(),a.user_id,n),await auditStmt(c.env,a.user_id,"STOCK_MOVEMENT","stock_movement",mid,`${p.name}: ${type} ${qty} ${p.unit}`,null,b,ipOf(c))]);const bal=await c.env.DB.prepare("SELECT p.opening_stock+COALESCE(SUM(CASE WHEN sm.status='AKTIF' AND sm.movement_type='IN' THEN sm.qty WHEN sm.status='AKTIF' AND sm.movement_type='OUT' THEN -sm.qty WHEN sm.status='AKTIF' AND sm.movement_type='ADJUSTMENT' THEN sm.qty ELSE 0 END),0) balance FROM products p LEFT JOIN stock_movements sm ON sm.product_id=p.id WHERE p.id=? GROUP BY p.id").bind(p.id).first();return c.json({ok:true,id:mid,balance:Number(bal.balance),negative:Number(bal.balance)<0},201);});

app.get("/api/settings",async c=>{const a=c.get("auth");if(!has(a,"settings.view")&&!has(a,"settings.manage"))return bad(c,"Tidak punya akses setting.",403);const r=await c.env.DB.prepare("SELECT key,value FROM settings ORDER BY key").all();return c.json({ok:true,settings:Object.fromEntries(r.results.map(x=>[x.key,x.value]))});});
app.put("/api/settings",async c=>{const a=c.get("auth");if(!has(a,"settings.manage"))return bad(c,"Tidak punya akses ubah setting.",403);const b=await c.req.json().catch(()=>({})),allowed=["clinic_name","clinic_tagline","default_ppn","invoice_prefix","per_visit_price"],stmts=[];for(const k of allowed)if(k in b)stmts.push(c.env.DB.prepare("INSERT INTO settings(key,value,updated_by,updated_at) VALUES(?,?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_by=excluded.updated_by,updated_at=excluded.updated_at").bind(k,String(b[k]),a.user_id,nowISO()));stmts.push(await auditStmt(c.env,a.user_id,"UPDATE_SETTINGS","settings","general","Pengaturan umum diperbarui",null,b,ipOf(c)));await c.env.DB.batch(stmts);return c.json({ok:true});});

app.get("/api/users",async c=>{const a=c.get("auth");if(!has(a,"users.view")&&!has(a,"users.manage"))return bad(c,"Tidak punya akses user.",403);const users=await c.env.DB.prepare("SELECT id,username,full_name,role,active,created_at FROM users ORDER BY full_name").all(),perms=await c.env.DB.prepare("SELECT user_id,permission FROM user_permissions WHERE allowed=1").all(),map={};for(const p of perms.results)(map[p.user_id]??=[]).push(p.permission);return c.json({ok:true,users:users.results.map(u=>({...u,permissions:u.role==="SUPER_ADMIN"?Object.keys(PERMISSIONS):(map[u.id]||[])})),permissionCatalog:PERMISSIONS,roleDefaults:ROLE_DEFAULTS,roles:ROLES});});
app.post("/api/users",async c=>{const a=c.get("auth");if(!has(a,"users.manage"))return bad(c,"Tidak punya akses kelola user.",403);const b=await c.req.json().catch(()=>({})),username=String(b.username||"").trim(),full=String(b.full_name||"").trim(),password=String(b.password||""),role=ROLES.includes(b.role)?b.role:"FRONT_OFFICE";if(!username||!full||password.length<8)return bad(c,"Nama, username, dan password minimal 8 karakter wajib.");if(await c.env.DB.prepare("SELECT id FROM users WHERE username=? COLLATE NOCASE").bind(username).first())return bad(c,"Username sudah digunakan.");const uid=id("usr"),n=nowISO(),hash=await hashPassword(password),perms=role==="SUPER_ADMIN"?Object.keys(PERMISSIONS):(Array.isArray(b.permissions)?b.permissions:ROLE_DEFAULTS[role]||[]);await c.env.DB.batch([c.env.DB.prepare("INSERT INTO users(id,username,full_name,password_hash,role,active,created_at,updated_at) VALUES(?,?,?,?,?,1,?,?)").bind(uid,username,full,hash,role,n,n),...perms.filter(p=>p in PERMISSIONS).map(p=>c.env.DB.prepare("INSERT INTO user_permissions(user_id,permission,allowed) VALUES(?,?,1)").bind(uid,p)),await auditStmt(c.env,a.user_id,"CREATE_USER","user",uid,`${username} (${role})`,null,{username,full,role,permissions:perms},ipOf(c))]);return c.json({ok:true,id:uid},201);});
app.put("/api/users/:id/permissions",async c=>{const a=c.get("auth");if(a.role!=="SUPER_ADMIN")return bad(c,"Hanya Super Admin yang dapat mengubah permission.",403);const uid=c.req.param("id"),u=await c.env.DB.prepare("SELECT * FROM users WHERE id=?").bind(uid).first();if(!u)return bad(c,"User tidak ditemukan.",404);const b=await c.req.json().catch(()=>({})),role=ROLES.includes(b.role)?b.role:u.role,active=b.active===false?0:1,perms=Array.isArray(b.permissions)?b.permissions.filter(p=>p in PERMISSIONS):[];if(uid===a.user_id&&(!active||role!=="SUPER_ADMIN"))return bad(c,"Super Admin tidak boleh menonaktifkan/menurunkan akun sendiri.");await c.env.DB.batch([c.env.DB.prepare("UPDATE users SET role=?,active=?,updated_at=? WHERE id=?").bind(role,active,nowISO(),uid),c.env.DB.prepare("DELETE FROM user_permissions WHERE user_id=?").bind(uid),...(role==="SUPER_ADMIN"?Object.keys(PERMISSIONS):perms).map(p=>c.env.DB.prepare("INSERT INTO user_permissions(user_id,permission,allowed) VALUES(?,?,1)").bind(uid,p)),await auditStmt(c.env,a.user_id,"UPDATE_USER_PERMISSIONS","user",uid,`Permission ${u.username} diperbarui`,{role:u.role,active:u.active},{role,active,permissions:perms},ipOf(c))]);return c.json({ok:true});});

app.get("/api/audit",async c=>{const a=c.get("auth");if(!has(a,"audit.view"))return bad(c,"Tidak punya akses audit.",403);const r=await c.env.DB.prepare("SELECT al.*,u.full_name,u.username FROM audit_logs al LEFT JOIN users u ON u.id=al.user_id ORDER BY al.created_at DESC LIMIT 200").all();return c.json({ok:true,logs:r.results});});
const csvEscape=v=>{const s=String(v??"");return /[\",\n]/.test(s)?`\"${s.replaceAll('"','""')}\"`:s;};
const toCSV=rows=>{if(!rows.length)return "";const cols=Object.keys(rows[0]);return [cols.join(","),...rows.map(r=>cols.map(k=>csvEscape(r[k])).join(","))].join("\n");};
app.get("/api/export/:type",async c=>{const a=c.get("auth");if(!has(a,"export.data"))return bad(c,"Tidak punya akses export.",403);const type=c.req.param("type");let rows,filename;if(type==="patients"){rows=(await c.env.DB.prepare("SELECT member_no,name,address,birth_date,phone,default_payment_mode,active,created_at FROM patients ORDER BY created_at").all()).results;filename="tangkas-pasien.csv";}else if(type==="visits"){rows=(await c.env.DB.prepare("SELECT v.visit_date,p.member_no,p.name,v.complaint,v.notes,v.payment_source,v.total_amount,v.payment_method,v.payment_status,v.status,v.created_at FROM visits v JOIN patients p ON p.id=v.patient_id ORDER BY v.visit_date,v.created_at").all()).results;filename="tangkas-kunjungan.csv";}else if(type==="stock"){rows=(await c.env.DB.prepare("SELECT sm.movement_date,p.sku,p.name,p.unit,sm.movement_type,sm.qty,sm.note,sm.status,sm.created_at FROM stock_movements sm JOIN products p ON p.id=sm.product_id ORDER BY sm.movement_date,sm.created_at").all()).results;filename="tangkas-stok.csv";}else return bad(c,"Jenis export tidak dikenal.",404);return new Response("\ufeff"+toCSV(rows),{headers:{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":`attachment; filename="${filename}"`}});});
app.get("/api/backup",async c=>{const a=c.get("auth");if(!has(a,"export.data"))return bad(c,"Tidak punya akses backup.",403);const tables=["patients","packages","patient_packages","visits","package_ledger","payments","products","stock_movements","settings","audit_logs"],data={generated_at:nowISO(),schema_version:1};for(const t of tables)data[t]=(await c.env.DB.prepare(`SELECT * FROM ${t}`).all()).results;return new Response(JSON.stringify(data,null,2),{headers:{"Content-Type":"application/json","Content-Disposition":`attachment; filename="tangkas-backup-${todayID()}.json"`}});});

app.notFound(c=>c.req.path.startsWith("/api/")?bad(c,"Endpoint tidak ditemukan.",404):c.env.ASSETS.fetch(c.req.raw));
app.onError((err,c)=>{console.error(err);return bad(c,"Terjadi kesalahan pada server.",500,{detail:err?.message});});
export default app;
